class: Workflow
cwlVersion: 1.2
inputs:
  JUMP:
    label: JUMP
    type: int
outputs:
  out:
    label: out
    outputSource: sum-84f8b7596e46f166d8cf6dde419dd64f/out
    type: int
steps:
  double-8cd109598b78ef1a86b350fcded44af7:
    in:
      num:
        source: increase-5b1704c47414b8603421781ceba7e969/out
    out:
    - out
    run: double
  increase-52073c03a5b4f5091a8e5d2cf3a5111b:
    in:
      JUMP:
        source: JUMP
      num:
        default: 17
    out:
    - out
    run: increase
  increase-5b1704c47414b8603421781ceba7e969:
    in:
      JUMP:
        source: JUMP
      num:
        default: 23
    out:
    - out
    run: increase
  increase-bd448c5983c6c4b03c912870e6960889:
    in:
      JUMP:
        source: JUMP
      num:
        source: increase-52073c03a5b4f5091a8e5d2cf3a5111b/out
    out:
    - out
    run: increase
  sum-84f8b7596e46f166d8cf6dde419dd64f:
    in:
      left:
        source: double-8cd109598b78ef1a86b350fcded44af7/out
      right:
        source: increase-bd448c5983c6c4b03c912870e6960889/out
    out:
    - out
    run: sum
