context:
  name: ${{ load_from_file("pyproject.toml").project.name }}
  version: ${{ load_from_file("pyproject.toml").project.version }}
  repository: ${{ load_from_file("pyproject.toml").project.repository }}

package:
  name: ${{ load_from_file("pyproject.toml").project.name }}
  version: ${{ load_from_file("pyproject.toml").project.version }}

source:
  - path: .

build:
  # Thanks to `noarch: python` this package works on all platforms
  noarch: python
  script:
    - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - hatchling
    - python ${{ load_from_file("pyproject.toml").project["requires-python"] }}
  run:
__PROJECT_DEPENDENCIES__

tests:
  - python:
      imports:
        - ${{ name }}
      pip_check: true
  - package_contents:
      site_packages:
        - dewret.workflow

about:
  homepage: ${{ load_from_file("pyproject.toml").project.homepage }}
  license: ${{ load_from_file("pyproject.toml").project.license }}
  summary: ${{ load_from_file("pyproject.toml").project.description }}
  description: |
__README__
  documentation: ${{ load_from_file("pyproject.toml").project.documentation }}
  repository: ${{ repository }}
